Config = {    

    OnlyforConcess = true, -- si le menu est accessible uniquement pour les personnes avec le job cardealerr

    PosConcess = vector3(-42.5,-1098, 26.4), -- position du concessionnaire (permet de  gerer la rotation des véhicules)

    PosMarker = vector3(-32.5, -1097.9, 26.4), -- Marker du menu de gestion

    Emplacement1 = { 
        {x = -42.9, y = -1102.7 ,z = 25.4, h= 0.0}, -- Posistion et heading de l'emplacement 1
    },

    Emplacement2 = {
        {x = -41.8, y = -1094.9 ,z = 26.4, h =150.0}, -- Posistion et heading de l'emplacement 2
    },

    Emplacement3 = {
        {x = -50.1, y = -1096.5 ,z = 26.4, h = 250.0}, -- Posistion et heading de l'emplacement 3
    },

    VoitureTourne = false, -- Choix de si les véhicules tourne ou non

    -- Config des véhicules

    Compact = {
        {label = "Blista", model = "blista"},
        {label = "Brioso R/A", model = "brioso"},
        {label = "Issi", model = "issi2"},
        {label = "Panto", model = "panto"},
        {label = "Prairie", model = "prairie"},
    },

    Coupes = {
        {label = "Cognoscenti Cabrio", model = "cogcabrio"},
        {label = "Exemplar", model = "exemplar"},
        {label = "F620", model = "f620"},
        {label = "Felon", model = "felon"},
        {label = "Felon GT", model = "felon2"},
        {label = "Jackal", model = "Jackal"},
        {label = "Oracle XS", model = "oracle2"},
        {label = "Sentinel", model = "sentinel"},
        {label = "Sentinel XS", model = "sentinel2"},
        {label = "Windsor", model = "windsor"},
        {label = "Windsor Drop", model = "windsor2"},
        {label = "Zion", model = "zion"},
        {label = "Zion Cabrio", model = "zion2"},
    },

    Muscle = {
        {label = "Blade", model = "blade"},
        {label = "Buccaneer", model = "buccaneer"},
        {label = "Buccaneer Rider", model = "buccaneer2"},
        {label = "Chino", model = "chino"},
        {label = "Chino Luxe", model = "chino2"},
        {label = "Coquette BlackFin", model = "coquette3"},
        {label = "Dominator", model = "dominator"},
        {label = "Dukes", model = "dukes"},
        {label = "Faction", model = "faction"},
        {label = "Faction Rider", model = "faction2"},
        {label = "Faction XL", model = "faction3"},
        {label = "Gauntlet", model = "gauntlet"},
        {label = "Hermes", model = "hermes"},
        {label = "Hotknife", model = "hotknife"},
        {label = "Nightshade", model = "nightshade"},
        {label = "Phoenix", model = "phoenix"},
        {label = "picador", model = "picador"},
        {label = "Ruiner 2", model = "ruiner2"},
        {label = "Sabre Turbo", model = "sabregt"},
        {label = "Sabre GT", model = "sabregt2"},
        {label = "Slam Van", model = "slamvan3"},
        {label = "Tampa", model = "tampa"},
        {label = "Vigero", model = "vigero"},
        {label = "Virgo", model = "virgo"},
        {label = "Voodoo", model = "voodoo"},
        {label = "Yosemite", model = "yosemite"},

    },

    Offroad = {
        {label = "Bf Injection", model = "bfinjection"},
        {label = "Bifta", model = "bifta"},
        {label = "Blazer", model = "blazer"},
        {label = "Blazer Sport", model = "blazer4"},
        {label = "Brawler", model = "brawler"},
        {label = "Dubsta 6x6", model = "dubsta3"},
        {label = "Dune Buggy", model = "dune"},
        {label = "Guardian", model = "guardian"},
        {label = "Kamacho", model = "kamacho"},
        {label = "Rebel", model = "rebel2"},
        {label = "Riata", model = "riata"},
        {label = "Sandking", model = "sandking"},
        {label = "Trophy Truck", model = "trophytruck"},
        {label = "Trophy Truck Limited", model = "trophytruck2"},
    },

    Sedans = {
        {label = "Asea", model = "asea"},
        {label = "Cognoscenti", model = "cognoscenti"},
        {label = "Emperor", model = "emperor"},
        {label = "Fugitive", model = "fugitive"},
        {label = "Glendale", model = "glendale"},
        {label = "Intruder", model = "intruder"},
        {label = "Premier", model = "premier"},
        {label = "Primo Custom", model = "primo2"},
        {label = "Regina", model = "regina"},
        {label = "Schafter", model = "schafter2"},
        {label = "Super Diamond", model = "superd"},
        {label = "Tailgater", model = "tailgater"},
        {label = "Warrener", model = "warrener"},
        {label = "Washington", model = "washington"},
    },

    Sport = {
        {label = "Alpha", model = "alpha"},
        {label = "Banshee", model = "banshee"},
        {label = "Bestia GTS", model = "bestiagts"},
        {label = "Buffalo", model = "buffalo"},
        {label = "Buffalo S", model = "buffalo2"},
        {label = "Carbonizzare", model = "carbonizzare"},
        {label = "Comet", model = "comet2"},
        {label = "Comet Sport", model = "comet5"},
        {label = "Coquette", model = "coquette"},
        {label = "Elegy", model = "elegy2"},
        {label = "Feltzer", model = "feltzer2"},
        {label = "Furore GT", model = "furoregt"},
        {label = "Fusilade", model = "fusilade"},
        {label = "Jester", model = "jester"},
        {label = "Jester(Racecar)", model = "jester2"},
        {label = "Khamelion", model = "khamelion"},
        {label = "Kuruma", model = "kuruma"},
        {label = "Lynx", model = "lynx"},
        {label = "Mamba", model = "mamba"},
        {label = "Massacro", model = "massacro"},
        {label = "Massacro(Racecar)", model = "massacro2"},
        {label = "9F", model = "ninef"},
        {label = "9F Cabrio", model = "ninef2"},
        {label = "Omnis", model = "omnis"},
        {label = "Pariah", model = "pariah"},
        {label = "Penumbra", model = "penumbra"},
        {label = "Raiden", model = "raiden"},
        {label = "Rapid GT", model = "rapidgt"},
        {label = "Rapid GT Convertible", model = "rapidgt2"},
        {label = "Revolter", model = "revolter"},
        {label = "Schafter V12", model = "schafter3"},
        {label = "Sentinel 3", model = "sentinel3"},
        {label = "Seven 70", model = "seven70"},
        {label = "Streiter", model = "streiter"},
        {label = "Sultan", model = "sultan"},
        {label = "Surano", model = "surano"},
        {label = "Drift Tampa", model = "tampa2"},
        {label = "Tropos", model = "tropos"},
        {label = "Verlierer", model = "verlierer2"},
    },

    Sportclassique = {
        {label = "Ardent", model = "ardent"},
        {label = "Btype", model = "btype"},
        {label = "Btype Hotroad", model = "btype2"},
        {label = "Btype Luxe", model = "btype3"},
        {label = "Casco", model = "casco"},
        {label = "Coquette Classic", model = "coquette2"},
        {label = "Stirling GT", model = "feltzer3"},
        {label = "GT 500", model = "gt500"},
        {label = "Manana", model = "manana"},
        {label = "Monroe", model = "monroe"},
        {label = "Pigalle", model = "pigalle"},
        {label = "Rapid GT3", model = "rapidgt3"},
        {label = "Retinue", model = "retinue"},
        {label = "Savestra", model = "savestra"},
        {label = "Stinger", model = "stinger"},
        {label = "Stinger GT", model = "stingergt"},
        {label = "Viseris", model = "viseris"},
        {label = "Z190", model = "z190"},
        {label = "Z-Type", model = "ztype"},
    },

    Super = {
        {label = "Adder", model = "adder"},
        {label = "Autarch", model = "autarch"},
        {label = "Banshee 900R", model = "banshee2"},
        {label = "Bullet", model = "bullet"},
        {label = "Cheetah", model = "cheetah"},
        {label = "Cyclone", model = "cyclone"},
        {label = "Entity XF", model = "entityxf"},
        {label = "FMJ", model = "fmj"},
        {label = "Infernus", model = "infernus"},
        {label = "RE-7B", model = "le7b"},
        {label = "Neon", model = "neon"},
        {label = "Osiris", model = "osiris"},
        {label = "Pfister", model = "pfister811"},
        {label = "X80 Proto", model = "prototipo"},
        {label = "Reaper", model = "reaper"},
        {label = "SC 1", model = "sc1"},
        {label = "ETR1", model = "sheava"},
        {label = "Sultan RS", model = "sultanrs"},
        {label = "T20", model = "t20"},
        {label = "Turismo R", model = "turismor"},
        {label = "Tyrus", model = "tyrus"},
        {label = "Vacca", model = "vacca"},
        {label = "Visione", model = "visione"},
        {label = "Voltic", model = "voltic"},
        {label = "Zentorno", model = "zentorno"},
    },

    Suv = {
        {label = "Baller", model = "baller2"},
        {label = "Baller Sport", model = "baller3"},
        {label = "Cavalcade", model = "cavalcade2"},
        {label = "Contender", model = "contender"},
        {label = "Dubsta", model = "dubsta"},
        {label = "Dubsta Luxuary", model = "dubsta2"},
        {label = "Fhantom", model = "fq2"},
        {label = "Granger", model = "granger"},
        {label = "Gresley", model = "gresley"},
        {label = "Huntley S", model = "huntley"},
        {label = "Landstalker", model = "landstalker"},
        {label = "Mesa", model = "mesa"},
        {label = "Mesa Trail", model = "mesa3"},
        {label = "Patriot", model = "patriot"},
        {label = "Radius", model = "radius"},
        {label = "Rocoto", model = "rocoto"},
        {label = "Seminole", model = "seminole"},
        {label = "XLS", model = "xls"},
    },

    Van = {
        {label = "Bison", model = "bison"},
        {label = "Bobcat XL", model = "bobcatxl"},
        {label = "Burrito", model = "burrito3"},
        {label = "Camper", model = "camper"},
        {label = "Gang Burrito", model = "gburrito"},
        {label = "Burrito", model = "gburrito2"},
        {label = "Journey", model = "journey"},
        {label = "Minivan", model = "minivan"},
        {label = "Moonbeam", model = "moonbeam"},
        {label = "Moonbeam Rider", model = "moonbeam2"},
        {label = "Paradise", model = "paradise"},
        {label = "Rumpo", model = "rumpo"},
        {label = "Rumpo Trail", model = "rumpo3"},
        {label = "Slam Van", model = "slamvan3"},
        {label = "Surfer", model = "surfer"},
        {label = "Youga", model = "youga"},
        {label = "Youga Luxuary", model = "youga2"},
    },
}